#!/usr/bin/env node

// This script reads the "oldReferencesReport.csv" generated by imgCheckOldReferences.js
// and updates ONLY those specific old references in the listed files.
// It does NOT re-scan the project, and does NOT replace anything else.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { parse } from "csv-parse";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// CSV columns: file, line, oldRef, newRef
const REPORT_CSV = path.join(__dirname, "oldReferencesReport.csv");

async function parseReportCSV() {
  const records = [];
  const parser = fs
    .createReadStream(REPORT_CSV)
    .pipe(parse({ delimiter: "," }));

  for await (const record of parser) {
    // [filePath, lineNumber, oldRef, newRef]
    records.push({
      file: record[0],
      line: Number(record[1]),
      oldRef: record[2],
      newRef: record[3],
    });
  }

  return records;
}

async function applyFixes(records) {
  // Group by file so we read/write each file once
  const byFile = {};

  for (const r of records) {
    if (!byFile[r.file]) byFile[r.file] = [];
    byFile[r.file].push(r);
  }

  for (const filePath in byFile) {
    try {
      let content = await fs.promises.readFile(filePath, "utf8");
      let lines = content.split("\n");

      let modified = false;

      for (const entry of byFile[filePath]) {
        const lineIndex = entry.line - 1;

        if (!lines[lineIndex]) continue;

        if (lines[lineIndex].includes(entry.oldRef)) {
          lines[lineIndex] = lines[lineIndex].replaceAll(
            entry.oldRef,
            entry.newRef,
          );
          modified = true;

          console.log(
            `### Updated ${filePath}:${entry.line}\n   ${entry.oldRef} -> ${entry.newRef}`,
          );
        }
      }

      if (modified) {
        await fs.promises.writeFile(filePath, lines.join("\n"), "utf8");
      }
    } catch (err) {
      console.error(`--- ERROR processing file ${filePath}:`, err.message);
    }
  }
}

async function run() {
  console.log("### Reading oldReferencesReport.csv...");
  const records = await parseReportCSV();

  if (records.length === 0) {
    console.log("### No entries found. Nothing to update.");
    return;
  }

  console.log("### Applying fixes...");
  await applyFixes(records);

  console.log("### DONE: All remaining old references have been fixed.");
}

await run();
